# This is the image we want to build from, but we want to build from it in a way
# that use repo2docker to extend it if possible somehow.
#
# ref: https://github.com/pangeo-data/pangeo-docker-images
#
# To accomplish the repo2docker extensions of this base image, I think we need
# to do something like this, but that is from the old repository and such
# -onbuild image has not been updated for ~4 months currently and doesn't have
# the latest dask-gateway versions etc.
#
# ref: https://github.com/pangeo-data/pangeo-stacks#customize-images-with-the--onbuild-variants
#
FROM pangeo/base-notebook:2020.11.18
